# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb1206dd081fa2675c4e9e04c69bc52034d4c1589c0e587d00457ef493461963fcfdc00f608f6f5c81ea0d72021bad5d1fa56eea3c3e7311a547e3cf1d5ec777

test:
  secret_key_base: 4ec22116c8db234889851caab457f745aedead09312beea0159adf9b994d3ce31324932e14f14efb303ffbeb70cbb762a77e8eec7b0214c8cbd077e015eab515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
